name: Publish Extension

on:
  workflow_dispatch:
  push:
    branches:
      - main
    paths:
      - package.json

jobs:
  publish:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: 18
          registry-url: https://registry.npmjs.org/

      - name: Install pnpm
        uses: pnpm/action-setup@v3
        with:
          version: latest

      - name: Get pnpm store directory
        id: pnpm-cache
        run: |
          echo "STORE_PATH=$(pnpm store path)" >> $GITHUB_OUTPUT

      - name: Setup pnpm cache
        uses: actions/cache@v4
        with:
          path: ${{ steps.pnpm-cache.outputs.STORE_PATH }}
          key: ${{ runner.os }}-pnpm-store-${{ hashFiles('**/pnpm-lock.yaml') }}
          restore-keys: |
            ${{ runner.os }}-pnpm-store-

      - name: Install dependencies
        run: pnpm install

      - name: Install ovsx
        run: pnpm add -g ovsx

      - name: Build extension
        run: pnpm run build

      - name: Publish to Visual Studio Marketplace
        run: npx vsce publish --no-dependencies -p ${{ secrets.VSCE_PAT }}
        env:
          VSCE_PAT: ${{ secrets.VSCE_PAT }}

      - name: Publish to Open VSX
        run: |
          npx ovsx publish --no-dependencies -p ${{ secrets.OVSX_PAT }} --extensionKind workspace --packagePath "." -o abei
        env:
          OVSX_PAT: ${{ secrets.OVSX_PAT }}
        if: success()
